### ISSUE TITLE
Create a S3 only backend

### ISSUE THREAD

**Issue by bjinwright** [kevproject/kev#10]

**Comment by mcrowson** [comment]
Any ideas on how to make this happen? I'd love to help as s3nosql would be a huge cost savings to any project.

**Comment by bjinwright** [comment]
I am working on it.The tricky part is creating a new I'd scheme for  S3.

**Comment by bjinwright** [comment]
This is what I came up with for the PK

```
import hashlib
import json
import six
import uuid
import datetime

doc_example = {'first':'John','last':'Doe','date_created':str(datetime.datetime.now()),'uuid':str(uuid.uuid4())}

pk = hashlib.md5(six.b(json.dumps(doc_example))).hexdigest()
```

**Comment by mcrowson** [comment]
Wouldn't the PK change every time the document changed? Why not just the uuid of the document?

**Comment by bjinwright** [comment]
No, just the first time. Because according to Amazon's best practices md5 hashes are more random.

**Comment by bjinwright** [comment]
I think I've solved the secondary index part I just need to fix the parsing of ids and figure out to do multiple filters at once. Since there is no intersection.
https://github.com/kevproject/kev/blob/feature/s3only/kev/backends/s3/db.py#L68

**Comment by mcrowson** [comment]
I was attempting to add placebo for the boto3 tests, but the way that the handler is passed around I couldn't find a way to create a session object in the test and pass it to the S3DB.

**Comment by bjinwright** [comment]
Complete
